### ISSUE TITLE
What is 'remram'?

### ISSUE THREAD

**Issue by remram44** [gtkatakura/remram#2]
Sooner or later I was bound to see an NPM package with my handle 😂
But what is it? 🤔

**Comment by gtkatakura** [comment]
A utility library (like lodash, ramda, etc) written in ECMAScript 2015...

I'm developing it to test various "market" tools (travis-ci, dependency-ci, snyk, david-dm, codeclimate, coveralls, codecov, codacy, commitizen, standard-version, etc) and decide which ones are the best.

**Comment by gtkatakura** [comment]
The name of the project is based on the Rem and Ram sisters [(Re:Zero)](https://pt.wikipedia.org/wiki/Re:Zero_Kara_Hajimeru_Isekai_Seikatsu).

;)
